version: '3.1'

services:
  momentum-backend:
    image: ghcr.io/bp-momentum/backend:latest
    restart: unless-stopped
    container_name: momentum-backend
    environment:
      EMAIL_ADDRESS: test@example.com
      EMAIL_PASSWORD: test
      EMAIL_HOST: smtp.example.com
      DATABASE_USE_POSTGRESQL: false
      VIDEO_PATH: videos
      ALLOWED_ORIGINS: http://localhost:8080  # CORS (urls that the frontend uses as a referer (frontend urls))
      ALLOWED_HOSTS: 127.0.0.1,localhost,backend.local  # Hosts that the backend answers to (backend urls)
    ports:
      - "8081:80"

  momentum-frontend:
    image: ghcr.io/bp-momentum/frontend:latest
    restart: unless-stopped
    container_name: momentum-frontend
    depends_on:
      - momentum-backend
    environment:
      BACKEND_URL: http://localhost:8081
      WEBSOCKET_URL: ws://localhost:8081
      FRONTEND_URL: http://localhost:8080/#/
    ports:
      - "8080:80"