version: '3.1'

services:
  momentum-ai:
    image: ghcr.io/bp-momentum/ai:latest
    restart: unless-stopped
    container_name: momentum-ai
    environment:
      BACKEND_URL: http://momentum-backend
      BACKEND_PSK: 1234

  momentum-backend:
    image: ghcr.io/bp-momentum/backend:latest
    restart: unless-stopped
    container_name: momentum-backend
    depends_on:
      - momentum-ai
    environment:
      EMAIL_ADDRESS: test@example.com
      EMAIL_PASSWORD: test
      EMAIL_HOST: smtp.example.com
      DATABASE_USE_POSTGRESQL: "false"
      VIDEO_PATH: videos
      ALLOWED_ORIGINS: http://localhost:8082  # CORS (urls that the frontend uses as a referer (frontend urls))
      ALLOWED_HOSTS: 127.0.0.1,localhost,backend.local  # Hosts that the backend answers to (backend urls)
      AI_URL: http://momentum-ai
      AI_PSK: 1234
    ports:
      - "8081:80"
    volumes:
      - ./exercise.json:/app/exercises.json

  momentum-frontend:
    image: ghcr.io/bp-momentum/frontend:latest
    restart: unless-stopped
    container_name: momentum-frontend
    depends_on:
      - momentum-backend
    environment:
      BACKEND_URL: http://localhost:8081
      WEBSOCKET_URL: ws://localhost:8081
      FRONTEND_URL: http://localhost:8082/#/
      DEBUG: true
    ports:
      - "8082:80"